### ISSUE TITLE
关于突然在某个群无法使用的情况

### ISSUE THREAD

**Issue by Akineru** [azmiao/good_morning#4]
今天在大群里突然发现早安晚安命指令无效了，但之前是一直正常的，去自己的小群测试是可以用的。大群的指令报错如下：
[2022-07-07 10:36:34,905 good_morning] ERROR: <class 'json.decoder.JSONDecodeError'> occured when good_night handling message -1116494203.
[2022-07-07 10:36:34,910 good_morning] ERROR: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\Administrator\Downloads\HoshinoBot\hoshino\service.py", line 224, in wrapper
    return await func(bot, event)
  File "C:\Users\Administrator\Downloads\HoshinoBot\hoshino\modules\good_morning\__init__.py", line 91, in good_night
    msg = get_night_msg(group_id, user_id, sex_str)
  File "C:\Users\Administrator\Downloads\HoshinoBot\hoshino\modules\good_morning\get_night.py", line 80, in get_night_msg
    data = json.load(file)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by azmiao** [comment]
看看你插件目录下的`data/大群群号.json`里面的内容

**Comment by Akineru** [comment]
是空白的

**Comment by azmiao** [comment]
那就把它里面整个换成：
'''
{
    "today_count": {
        "morning": 0,
        "night": 0
    }
}
'''

**Comment by Akineru** [comment]
可以了，十分感谢帮助

**Comment by azmiao** [comment]
没事，这垃圾代码写的太烂了，可能容易出BUG，等我以后有空重构一下吧2333
